# GitHub Action for deploying a Laravel project to Hostinger via FTP

name: Deploy to Hostinger

# Triggers the workflow on a push event to the 'main' branch
on:
  push:
    branches:
      - main  # Or 'master', or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up PHP environment
      # ⚠️ IMPORTANT: Change '8.2' to match your project's PHP version
      # Check your composer.json file for the "php" requirement (e.g., "^8.1")
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # <-- CHECK AND CHANGE THIS
          extensions: mbstring, xml, ctype, json, tokenizer, dom, pdo_mysql
          tools: composer
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4. Set up Node.js (for building CSS/JS)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your project's node version

      # 5. Install NPM dependencies and build assets
      - name: Install NPM dependencies
        run: npm install
      - name: Build assets
        run: npm run build

      # 6. Run Laravel optimizations
      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
       
      - name: Remove node_modules
        run: rm -rf node_modules   

      # 7. Deploy files to server via FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /renzman-booking-system/

          # Exclude files that don't need to be on the server
          # This prevents overwriting your .env file!
          exclude: |
            **/.git*
            **/.github*
            **/node_modules*
            .editorconfig
            .env
            .env.example
            .gitignore
            composer.json
            composer.lock
            package.json
            package-lock.json
            phpunit.xml
            README.md
            vite.config.js
            /storage/logs/*
            /storage/framework/cache/*
            /storage/framework/sessions/*
            /storage/framework/views/*