name: Deploy Laravel to Hostinger

# This action runs on every push to the 'main' branch
on:
  push:
    branches:
      - main  # Change this to 'master' if that's your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use a standard Linux runner

    steps:
    # 1. Get the latest code from your repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up the PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Match your Hostinger PHP version
        extensions: mbstring, dom, fileinfo, mysql
        
    # 3. Install Composer (PHP) dependencies
    - name: Install Composer Dependencies
      run: composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

    # 4. Set up Node.js to build your assets (CSS/JS)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Match your local version
        
    # 5. Install NPM (JS) dependencies and build assets
    - name: Install NPM Dependencies and Build
      run: |
        npm install
        

    # 6. Create the production .env file from your GitHub Secret
    - name: Create .env file
      run: echo "${{ secrets.PROD_ENV }}" > .env

    # 7. Generate a new app key (if not set in your secret) and optimize Laravel
    - name: Run Laravel optimizations
      run: |
        php artisan key:generate --force
        php artisan config:cache
        php artisan route:cache
        
        

    # 8. Get list of changed files
    - name: Get list of changed files
      id: changed-files
      run: |
        echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')" >> $GITHUB_ENV

    # 9. Upload only changed files via lftp
    - name: Upload changed files via lftp
      env:
        FTP_HOST: 145.79.28.22
        FTP_USER: u689011157
        FTP_PASS: Rg34f/7rewzeUaj.
        FTP_TARGET: /public_html/
        CHANGED_FILES: ${{ env.CHANGED_FILES }}
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        for file in $CHANGED_FILES; do
          if [ -f "$file" ]; then
            lftp -u "$FTP_USER","$FTP_PASS" -e "set ftp:ssl-allow no; put -O $FTP_TARGET $file; bye" $FTP_HOST
          fi
        done

