name: Deploy to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, xml, curl, openssl

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Install Node & build assets (if present)
        run: |
          if [ -f package.json ]; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            npm ci
            npm run prod || npm run build || true
          fi

      # Prepare known_hosts so SSH-based steps don't prompt
      - name: Prepare SSH known_hosts (only for SFTP)
        if: ${{ secrets.HOSTINGER_DEPLOY_METHOD == 'sftp' }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.HOSTINGER_PORT }} ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts

      # SFTP/SSH (SCP/rsync) deployment
      - name: Deploy via SFTP (SCP)
        if: ${{ secrets.HOSTINGER_DEPLOY_METHOD == 'sftp' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          port: ${{ secrets.HOSTINGER_PORT }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          passphrase: ${{ secrets.HOSTINGER_SSH_PASSPHRASE }}
          source: "."
          target: ${{ secrets.HOSTINGER_REMOTE_PATH }}

      # FTP deployment (use this if you only have FTP credentials)
      - name: Deploy via FTP
        if: ${{ secrets.HOSTINGER_DEPLOY_METHOD == 'ftp' }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          local-dir: .
          server-dir: ${{ secrets.HOSTINGER_REMOTE_PATH }}
          excludes: |
            .git*
            .github*
            node_modules
            vendor
            .env

      # OPTIONAL: run remote artisan migrate (SSH required)
      # Uncomment and use only if you want GitHub Actions to run migrations remotely.
      # - name: Run remote migrations
      #   if: ${{ secrets.HOSTINGER_DEPLOY_METHOD == 'sftp' }}
      #   run: |
      #     ssh -p ${{ secrets.HOSTINGER_PORT }} -i /tmp/ssh_key -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }} "cd ${{ secrets.HOSTINGER_REMOTE_PATH }} && php artisan migrate --force"
